load("//tests:defs.bzl", "nsis_installer_test")
load("//nsis:defs.bzl", "nsis_component", "nsis_component_group", "nsis_installer", "nsis_directory")
load("@rules_python//python:pip.bzl", "compile_pip_requirements")
load("@rules_python//python:py_binary.bzl", "py_binary")

exports_files([
    "__init__.py",
    "nsis_install_test.py",
], ["//visibility:private"])

package(default_visibility = ["//visibility:private"])

compile_pip_requirements(
    name = "requirements",
    src = "requirements.txt",
    requirements_txt = "requirements_lock_txt",
)

filegroup(
    name = "nsis_files",
    srcs = [
        "//tests/testdata:README.md",
    ],
)

nsis_component(
    name = "minimal_component",
    srcs = [":nsis_files"],
    selection_mode = "default",
)

nsis_installer(
    name = "minimal_installer",
    id = "8d5d6365-eccc-48aa-9dff-4baf9e206fc0",
    components = [":minimal_component"],
    product = "Minimal Installer",
    product_path = "Minimal Installer",
)

nsis_installer(
    name = "minimal_installer_outfile",
    id = "e6885d94-b532-4a03-970a-7d37283945b2",
    components = [":minimal_component"],
    product = "Minimal Installer",
    product_path = "Minimal Installer",
    outfile = "Hello World.exe",
)

nsis_installer_test(
    name = "minimal_installer_outfile_test",
    installer = ":minimal_installer_outfile",
    must_have_paths = ["README.md"],
)

nsis_component(
    name = "minimal_component_depsA",
    srcs = [":nsis_files"],
    selection_mode = "optional",
)

nsis_component(
    name = "minimal_component_depsB",
    srcs = [":nsis_files"],
    dependencies = [
        ":minimal_component",
        ":minimal_component_depsA",
    ],
    selection_mode = "optional",
)

nsis_component(
    name = "minimal_component_depsC",
    srcs = [":nsis_files"],
    dependencies = [
        ":minimal_component_depsB",
    ],
    selection_mode = "optional",
)

nsis_installer(
    name = "minimal_installer_deps",
    id = "54929554-846d-45fb-b2f4-05da614053ce",
    components = [
        ":minimal_component",
        ":minimal_component_depsA",
        ":minimal_component_depsB",
        ":minimal_component_depsC",
    ],
    product = "Minimal Installer Deps",
    product_path = "Minimal Installer Deps",
)

nsis_installer_test(
    name = "minimal_installer_test_deps",
    installer = ":minimal_installer_deps",
    must_have_paths = ["README.md"],
)

nsis_component(
    name = "single_service_component",
    service = True,
    service_executable = "//tests/testdata:README.md",
    service_start_type = "auto",
    selection_mode = "required",
    display_name = "README Service",
    description = "README Service Description",
    install_categories = ["Full", "Typical", "Minimal"],
    srcs = [":nsis_files"],
)

nsis_installer(
    name = "single_service_installer",
    id = "93061bb4-387d-4653-aef0-396ea6573afc",
    product = "Single Service Installer",
    product_path = "SSI",
    eventlog = True,
    vendor = "Company Department",
    vendor_path = "Company\\Department",
    description = "Description",
    version = "0.0.0.1",
    execution_level = "admin",
    components = [
        ":single_service_component",
    ],
    install_categories = [
        "Full",
        "Typical",
        "Minimal",
    ],
)

nsis_installer_test(
    name = "single_service_test",
    installer = ":single_service_installer",
    must_have_paths = ["README.md"],
)

nsis_component_group(
    name = "minimal_group",
    components = [
        ":minimal_component"
    ],
)

nsis_installer(
    name = "minimal_installer_with_group",
    id = "0ba7fe50-2dc5-4d43-8c7d-309ce7f0d28c",
    components = [":minimal_group"],
    product = "Minimal Installer Group",
    product_path = "Minimal Installer Group",
)

nsis_installer_test(
    name = "minimal_installer_with_group_test",
    installer = ":minimal_installer_with_group",
    must_have_paths = ["README.md"],
)

nsis_component(
    name = "minimal_component_with_dir",
    directory = "Component",
    srcs = [":nsis_files"],
)

nsis_installer(
    name = "minimal_installer_with_dir",
    id = "053d27a9-f532-4b69-9ede-42bb634de08b",
    components = [":minimal_component_with_dir"],
    product = "Minimal Installer Dir",
    product_path = "Minimal Installer Dir",
)

nsis_installer_test(
    name = "minimal_installer_with_dir_test",
    installer = ":minimal_installer_with_dir",
    must_have_paths = ["Component/README.md"],
)

nsis_component(
    name = "ssc_with_group_and_dir_component",
    directory = "Component",
    service = True,
    service_executable = "//tests/testdata:README.md",
    service_start_type = "auto",
    selection_mode = "required",
    display_name = "README Service GrpDir",
    description = "README Service Description",
    install_categories = ["Full", "Typical", "Minimal"],
    srcs = [":nsis_files"],
)

nsis_component_group(
    name = "ssc_with_group_and_dir_group",
    components = [
        ":ssc_with_group_and_dir_component"
    ],
)

nsis_installer(
    name = "ssc_with_group_and_dir",
    id = "7cb8f799-ce8b-41d8-94d1-717e9fd56217",
    product = "Single Service Installer GrpDir",
    product_path = "SSI",
    vendor = "Company Department",
    vendor_path = "Company\\Department",
    description = "Description",
    version = "0.0.0.1",
    execution_level = "admin",
    components = [
        ":ssc_with_group_and_dir_group",
    ],
    install_categories = [
        "Full",
        "Typical",
        "Minimal",
    ],
)

nsis_installer_test(
    name = "ssc_with_group_and_dir_test",
    installer = ":ssc_with_group_and_dir",
    must_have_paths = ["Component\\README.md"],
)

nsis_installer(
    name = "minimal_installer_with_nostamp",
    id = "e7598904-2a8f-4f07-a7b8-c56472237744",
    components = [":minimal_component"],
    product = "Minimal Installer STAMP",
    stamp = 0,
    product_path = "Minimal Installer STAMP",
    version = "{STABLE_VERSION}"
)

nsis_installer_test(
    name = "minimal_installer_with_nostamp_test",
    installer = ":minimal_installer_with_nostamp",
    must_have_paths = ["README.md"],
)

nsis_installer(
    name = "minimal_installer_with_stamp_default",
    id = "a66e7e6c-7f1c-421f-b10d-54b2af0db5a6",
    components = [":minimal_component"],
    product = "Minimal Installer STAMP2",
    product_path = "Minimal Installer STAMP2",
    version = "{STABLE_VERSION}",
    stamp_defaults = {
        "STABLE_VERSION": "3.2.1.0",
    },
)

nsis_installer_test(
    name = "minimal_installer_with_stamp_default_test",
    installer = ":minimal_installer_with_stamp_default",
    must_have_paths = ["README.md"],
)

nsis_installer(
    name = "minimal_installer_with_nostamp_vendor",
    id = "d3b2f114-f5d2-4346-806b-f88ca707ce1d",
    components = [":minimal_component"],
    product = "Minimal Installer NoStamp Vendor",
    product_path = "Minimal Installer NoStamp Vendor",
    vendor = "{STABLE_VENDOR}",
    stamp = 0,
)

nsis_installer(
    name = "minimal_installer_with_stamp_vendor",
    id = "21fee1ca-dc02-4b44-a950-322283d2f6a3",
    components = [":minimal_component"],
    product = "Minimal Installer Vendor",
    product_path = "Minimal Installer Vendor",
    vendor = "{STABLE_TEST_VENDOR}",
    stamp = 1,
)

py_binary(
    name = "bin_with_runfiles",
    main = "dummy.py",
    srcs = [
        "dummy.py",
        "__init__.py",
    ],
    data = [
        ":nsis_files",
    ],
)

nsis_component(
    name = "minimal_component_runfiles",
    srcs = [
        ":bin_with_runfiles",
        ":nsis_files",
    ],
    selection_mode = "default",
)

nsis_installer(
    name = "minimal_installer_runfiles",
    id = "e517ee24-7f00-4b34-96e7-1c59ea712988",
    components = [":minimal_component_runfiles"],
    product = "Minimal Installer Runfiles",
    product_path = "Minimal Installer Runfiles",
)

nsis_installer_test(
    name = "minimal_installer_runfiles_test",
    installer = ":minimal_installer_runfiles",
    must_have_paths = [
        "README.md",
        "__init__.py",
        "dummy.py",
    ],
)

nsis_installer(
    name = "minimal_installerA",
    id = "8d5d6365-eccc-48aa-9dff-4baf9e206fc0",
    components = [":minimal_component"],
    product = "Minimal Installer A",
    product_path = "Minimal Installer",
)

nsis_installer(
    name = "minimal_installerB",
    id = "8d5d6365-eccc-48aa-9dff-4baf9e206fc0",
    components = [":minimal_component_with_dir"],
    product = "Minimal Installer B",
    product_path = "Minimal Installer",
)

nsis_installer_test(
    name = "install_first_and_remove_test",
    installer = ":minimal_installerA",
    install_first_and_remove = ":minimal_installerB",
)

nsis_installer(
    name = "minimal_installer_arch32_allowed_on64",
    id = "b540e991-9102-4082-b9aa-37c4d3e21817",
    components = [":minimal_component"],
    product = "Minimal Installer 32 allowed 64",
    product_path = "Minimal Installer",
    arch = "x86_32",
)

nsis_installer_test(
    name = "32bit_install_on_64bit",
    installer = ":minimal_installer_arch32_allowed_on64",
    target_compatible_with = ["@platforms//cpu:x86_64"]
)

nsis_installer(
    name = "minimal_installer_arch32_not_allowed_on64",
    id = "325cae94-81e8-4442-8d2b-6846edde35a7",
    components = [":minimal_component"],
    product = "Minimal Installer 32 not allowed 64",
    product_path = "Minimal Installer",
    arch = "x86_32",
    allow_32bit_on_64bit = False,
)

nsis_installer_test(
    name = "32bit_fail_install_on_64bit",
    installer = ":minimal_installer_arch32_not_allowed_on64",
    expect_failed_install = True,
    target_compatible_with = ["@platforms//cpu:x86_64"]
)

nsis_directory(
    name = "test_root_dir",
    path = "C:\\ROOT",
    grants = {
        "Everyone": "RW",
    },
)

nsis_component(
    name = "create_root_dir_component",
    dirs = [
        ":test_root_dir",
    ],
    selection_mode = "optional",
)

nsis_installer(
    name = "create_root_dir_installer",
    id = "887a81fc-cf67-42d9-aebb-9fab608f759c",
    components = [":create_root_dir_component"],
    product = "Create Root Dir Installer",
    product_path = "Create Root Dir Installer",
)
