load("@rules_nsis//nsis:defs.bzl", "nsis_component", "nsis_component_group", "nsis_installer")

nsis_component(
    name = "minimal_component",
    srcs = ["test.file"],
    selection_mode = "default",
)

nsis_installer(
    name = "minimal_installer",
    id = "9028ce71-646d-4949-910e-0dd8104eec31",
    components = [":minimal_component"],
    product = "Minimal Installer",
    product_path = "Minimal Installer",
)
