module(
    name = "rules_nsis-usagetest",
)

############################
# SETUP SIGNING
############################
bazel_dep(name = "rules_signing", version = "0.1.0")
archive_override(
    module_name = "rules_signing",
    sha256 = "53567d86d25c66e696f7ba96348a333490896b28d3322c32dccf8adb07f410ed",
    strip_prefix = "rules_signing-a2c724832a55767a9aa4aec51ed2338bb9168c4b",
    urls = ["https://github.com/EliSauder/rules_signing/archive/a2c724832a55767a9aa4aec51ed2338bb9168c4b.tar.gz"],
)

signing_tools = use_extension("@rules_signing//signing:extensions.bzl", "signing_tools")
signing_tools.openssl(path = "openssl")
use_repo(
    signing_tools,
    "signing_cosign",
    "signing_openssl",
    "signing_osslsigncode",
)
register_toolchains(
    "@signing_openssl//:openssl_toolchain",
    "@signing_cosign//:cosign_toolchain",
    "@signing_osslsigncode//:osslsigncode_toolchain",
)

bazel_dep(name = "rules_nsis", version = "0.1.0")
local_path_override(
    module_name = "rules_nsis",
    path = "../../",
)

nsis = use_extension("@rules_nsis//nsis:extensions.bzl", "nsis")
# Currently 3.11 is the only supported version.
nsis.executable(name = "nsis", version = "3.11")

use_repo(nsis, "nsis_tool", "nsis_toolchains")

register_toolchains("@nsis_toolchains//:all")
