module(
    name = "rules_nsis-usagetest",
)

############################
# SETUP SIGNING
############################
bazel_dep(name = "rules_signing", version = "0.1.0")
archive_override(
    module_name = "rules_signing",
    sha256 = "003ff01e635345e71bd38d0e186b6cfe1bac7ee4df1e4044400f2162f41a01b4",
    strip_prefix = "rules_signing-191325984aa0444588179abbf84e7abc06639825",
    urls = ["https://github.com/EliSauder/rules_signing/archive/191325984aa0444588179abbf84e7abc06639825.tar.gz"],
)

signing_tools = use_extension("@rules_signing//signing:extensions.bzl", "signing_tools")
signing_tools.openssl(path = "openssl")
use_repo(
    signing_tools,
    "signing_cosign",
    "signing_openssl",
    "signing_osslsigncode",
)
register_toolchains(
    "@signing_openssl//:openssl_toolchain",
    "@signing_cosign//:cosign_toolchain",
    "@signing_osslsigncode//:osslsigncode_toolchain",
)

bazel_dep(name = "rules_nsis", version = "0.1.0")
local_path_override(
    module_name = "rules_nsis",
    path = "../../",
)

nsis = use_extension("@rules_nsis//nsis:extensions.bzl", "nsis")
# Currently 3.11 is the only supported version.
nsis.executable(name = "nsis", version = "3.11")

use_repo(nsis, "nsis_tool", "nsis_toolchains")

register_toolchains("@nsis_toolchains//:all")
