name: test rules

on:
  pull_request:
  push:

jobs:
  windows-bazel-test:
    concurrency:
      group: ${{ github.workflow }}-windows-${{ github.ref }}
      cancel-in-progress: true
    runs-on: [windows-latest]
    steps:
      - name: bazel
        uses: bazel-contrib/setup-bazel@0.19.0
        with:
          bazelisk-cache: true
          disk-cache: ${{ github.workflow }}
          repository-cache: true
      - name: checkout
        uses: actions/checkout@v6
      - name: build
        run: bazel build //...
      - name: test
        run: bazel test //...
  linux-darwin-bazel-test:
    runs-on: [ubuntu-latest, macos-latest]
    concurrency:
      group: ${{ github.workflow }}-nonwindows-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: bazel
        uses: bazel-contrib/setup-bazel@0.19.0
        with:
          bazelisk-cache: true
          disk-cache: ${{ github.workflow }}
          repository-cache: true
      - name: checkout
        uses: actions/checkout@v6
      - name: build
        run: bazel build //...
      - name: test
        run: bazel test //...
