name: test rules

on:
  pull_request:
  push:

jobs:
  windows-bazel-test:
    concurrency:
      group: ${{ github.workflow }}-windows-${{ github.ref }}
      cancel-in-progress: true
    runs-on: [windows-latest]
    steps:
      - name: bazel
        uses: bazel-contrib/setup-bazel@0.19.0
        with:
          bazelisk-cache: true
          disk-cache: ${{ github.workflow }}-windows
          repository-cache: true
      - name: checkout
        uses: actions/checkout@v6
      - name: test
        run: bazel test //... --verbose_failures --sandbox_debug
  linux-bazel-test:
    runs-on: [ubuntu-latest]
    concurrency:
      group: ${{ github.workflow }}-linux-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: bazel
        uses: bazel-contrib/setup-bazel@0.19.0
        with:
          bazelisk-cache: true
          disk-cache: ${{ github.workflow }}
          repository-cache: true
      - name: checkout
        uses: actions/checkout@v6
      - name: test
        run: bazel test //... --verbose_failures --sandbox_debug
  macos-bazel-test:
    runs-on: [macos-latest]
    concurrency:
      group: ${{ github.workflow }}-macos-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: bazel
        uses: bazel-contrib/setup-bazel@0.19.0
        with:
          bazelisk-cache: true
          disk-cache: ${{ github.workflow }}
          repository-cache: true
      - name: checkout
        uses: actions/checkout@v6
      - name: test
        run: bazel test //... --verbose_failures --sandbox_debug
